services:
  talker1:
    build: .
    container_name: talker1
    restart: always
    command: bash -c "source install/setup.bash && ros2 run py_pubsub talker --ros-args -p number:=1"
  talker2:
    build: .
    container_name: talker2
    restart: always
    command: bash -c "source install/setup.bash && ros2 run py_pubsub talker --ros-args -p number:=2"
  listener:
    build: .
    container_name: listener
    restart: always
    command: bash -c "source install/setup.bash && ros2 run py_pubsub listener"
  
